FROM python:3.10-slim

# Instala ferramentas de rede E bc
RUN apt-get update && \
    apt-get install -y iproute2 iputils-ping bc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Cria diretório de trabalho
WORKDIR /app

# Copia o script de entrada (configura gateway e mantém container vivo)
COPY ./hosts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
