# docker/Dockerfile.roteador
FROM python:3.10-slim

RUN apt-get update && apt-get install -y iputils-ping iproute2 bc && apt-get clean

WORKDIR /app

# Copia código Python e configs
COPY routers/ /app/
COPY configs/ /app/configs/

EXPOSE 5000

CMD ["python", "-u", "router.py"]
